name         'stdmod-openssh'
version      '0.0.1'
author       'Stdmod authors'
license      'Apache2'
project_page 'https://github.com/stdmod'
source       'https://github.com/stdmod/puppet-openssh'
summary      'Puppet module for openssh'
description  'This module installs and manages openssh. Check README for details.'
dependency   'puppetlabs/stdlib', '>=2.0.0'
